### ISSUE TITLE
Support for Sailfish 4.6.0.x

### ISSUE THREAD

**Issue by theseer** [piggz/harbour-amazfish#381]
When upgrading from 4.5.x.y to 4.6.0.11 or 4.6.0.12,  amazfish has unresolvable dependencies to some ICU libraries.

Any chance to get an updated build for 4.6.0.x?

**Comment by omartijn** [comment]
Looking at the CI pipeline, it uses a docker image for the build environment. That one hasn't been updated yet.

**Comment by piggz** [comment]
Fixed and available in chum

**Comment by theseer** [comment]
Works like charm again :) Thanks a lot!

**Comment by jmlich** [comment]
I am not sure, but https://sailfishos-chum.github.io/apps/harbour-amazfish/ still shows version 2.2.4

**Comment by theseer** [comment]
I didn't actually verify the version itself. All I know is that I could now install it again without any issues and it runs like charm on 4.6.0.13.

**Comment by piggz** [comment]
Not sure how often that site updates, but version is 2.3.0 https://build.sailfishos.org/package/show/sailfishos:chum/harbour-amazfish
